# MySQLの公式イメージの中でも、Debian Bookworm (Debian 12) ベースのイメージを指定
FROM mysql:8.0.42-bookworm

# 環境変数でロケールを設定
ENV LANG ja_JP.UTF-8
ENV LC_ALL ja_JP.UTF-8

# 日本語ロケールをインストールするためのパッケージをインストールし、ロケールを生成
RUN apt-get update && \
    apt-get install -y locales && \
    rm -rf /var/lib/apt/lists/* && \
    echo "ja_JP.UTF-8 UTF-8" >> /etc/locale.gen && \
    locale-gen ja_JP.UTF-8 && \
    echo "export LANG=ja_JP.UTF-8" >> /etc/profile.d/locale.sh && \
    echo "export LC_ALL=ja_JP.UTF-8" >> /etc/profile.d/locale.sh

# タイムゾーンを設定
ENV TZ=Asia/Tokyo